module.exports = {
    MYSQL_ADDON_HOST: process.env.MYSQL_ADDON_HOST,
    MYSQL_ADDON_USER: process.env.MYSQL_ADDON_USER,
    MYSQL_ADDON_PORT: process.env.MYSQL_ADDON_PORT,
    MYSQL_ADDON_DB: process.env.MYSQL_ADDON_DB,
    MYSQL_ADDON_PASSWORD: process.env.MYSQL_ADDON_PASSWORD
}